server:
  port: 8000
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-request: true
      force-response: true
  tomcat:
    uri-encoding: UTF-8
    
    
spring:
#  security:
#    user:
#      name: test
#      password: 1234
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 314023522746-j57cm3sbdalnn0qjc8bf0mm8au788jbh.apps.googleusercontent.com
            client-secret: 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
            scope:
            - email
            - profile
          naver:
            client-id: HwANuSAJ6tbgu9AFmsJk
            client-secret: OLyBAcI7jg
            scope:
            - email
            - name
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8000/login/oauth2/code/naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token 
            user-info-uri: https://openapi.naver.com/v1/nid/me  
            user-name-attribute: response
  mvc:
    static-path-pattern: /static/**
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://web1.cgmmemndynvq.ap-northeast-2.rds.amazonaws.com:3306/study?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: admin
    password: 1q2w3e4r
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
        
        
    
mybatis:
  mapper-locations:
  - /mappers/*.xml

file:
  path: C:/Java/workspace/security_sanghyun/security_sanghyun/upload/